version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:9.9
        steps:
            - checkout
            - run: npm install
            - run: npm tsc -p tsconfig.json
            - run: CI=true npm run build
    test:
        docker:
            - image: circleci/node:9.9
        steps:
            - checkout
            - run: npm install
            - run: npm test
workflows:
    build_test_and_lint:
        jobs:
            - build
            - test
